@echo off
ECHO Transformujem %1 do XHTML podla %2...
ECHO Saxon...
java -jar "D:\Users\MatusPilnan\Desktop\Skola\6.semester\dalsieWpub\prezentacia\Saxon\saxon9he.jar" -o:output/output.html -s:%1 -xsl:%2 -ext:on
ECHO Hotovo.